# Generated by Django 5.2.7 on 2025-10-23 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Subtítulo"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="Imagen"),
                ),
                (
                    "favorited_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorite_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Favorito de",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
    ]
