# Generated by Django 5.2.7 on 2025-10-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="benefits",
            field=models.TextField(
                blank=True, null=True, verbose_name="Beneficios (separados por |)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descripción"),
        ),
        migrations.AddField(
            model_name="product",
            name="how_to_use",
            field=models.TextField(
                blank=True, null=True, verbose_name="Modo de empleo"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True, null=True, verbose_name="Ingredientes"),
        ),
        migrations.AddField(
            model_name="product",
            name="warnings",
            field=models.TextField(blank=True, null=True, verbose_name="Precauciones"),
        ),
    ]
