# Generated by Django 5.2.7 on 2025-10-27 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_product_benefits_product_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("chico", "Chico"),
                            ("mediano", "Mediano"),
                            ("grande", "Grande"),
                        ],
                        max_length=10,
                        verbose_name="Tamaño",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="core.product",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tamaño de producto",
                "verbose_name_plural": "Tamaños de productos",
                "unique_together": {("product", "size")},
            },
        ),
    ]
